### ISSUE TITLE
รูปหน้า Login แตก

### ISSUE THREAD

**Issue by MlDOR1** [Rawitath/We-Will-Cook#4]
![Screenshot 2024-10-12 125426](https://github.com/user-attachments/assets/fe5b2c2a-6d8d-4393-af8b-4542ded95f87)

![image](https://github.com/user-attachments/assets/7fee8092-d40d-485e-b6af-caa16b1843d2)

**Comment by Rawitath** [comment]
เดี๋ยวช่วย

**Comment by asiaapipoo** [comment]
เปลี่ยนให้ละ มีให้เลือก3-4รูปลองดูอันไหนเหมาะ

**Comment by Rawitath** [comment]
pull มาแล้ว ชัดกว่าอันเก่าเยอะมาก

**Comment by Rawitath** [comment]
ภาพหายแตกหมดละ close issue ละเด้อ
