### ISSUE TITLE
แก้โค้ดให้หน่อย

### ISSUE THREAD

**Issue by Rawitath** [Rawitath/We-Will-Cook#8]
(cooking/views.py)ขอ function show_recipe() เป็นแบบ class-based นะ
ex. `class ShowRecipeView(APIVIew):`
![Screenshot 2024-11-06 031842](https://github.com/user-attachments/assets/253ad180-ae8a-4208-aa3c-e40ef0bf39ca)
<br>
(cooking/urls.py)ตรงนี้ให้มี urlpatterns แค่อันเดียวพอ เอา path มารวมกันในอันเดียว
![Screenshot 2024-11-06 031831](https://github.com/user-attachments/assets/994549cb-be45-40b7-8527-d77286efaf82)
<br>
(.py) ไฟล์ไม่มีชื่อ อยู่นอก cooking และก็มี print ติดมา
![Screenshot 2024-11-06 031740](https://github.com/user-attachments/assets/5c094fab-70ff-4e51-b120-dfe424c476d4)

**Comment by BlackR-B** [comment]
fixed
